- groups.go
- groups_test.go
- support_groups_test.go
* Added support to delete groups
* Added tests
> Added support for delete group

- users.go
Allow changing passwords to users.
> Feature/Ernest 1870: 

- services.go
- services_test.go
Fixed, now it returns nothing to the CLI
> Ernest 1919: Cli breaks when getting a definition of a non existent service

- groups.go
- groups_test.go
- services_helpers.go
- setup.go
- users.go
- users_test.go
> Groups and datacenter endpoint implementation 

- datacenters.go
- services.go
- services_helpers.go
- services_test.go
Allow new POST datacenter fields to create and manage different provider based datacenters
> Basic AWS support

- services.go
- services_test.go
Fixes https://github.com/ernestio/ernest/issues/39
> Services list to return only last version of each service

- service_model.go
- service_renderer.go
Fixes https://github.com/ernestio/ernest/issues/43
> Exposes elb name and dns through the service details

- service_model.go
- service_renderer.go
> adding additional network field

- datacenter_model.go
- datacenters.go
- datacenters_test.go
- service_model.go
- services.go
Fixes https://github.com/ernestio/ernest/issues/67
> Allow datacenter deletion

- datacenter_model.go
- datacenters.go
Fixes https://github.com/ernestio/ernest/issues/67
> Allow datacenters update

- base_model.go
- error.go
- logger_model.go
- loggers.go
- setup.go
Fixes : https://github.com/ernestio/ernest/issues/84 by adding new endpoints to api-gateway in order to manage different loggers:
- GET /loggers
- POST /loggers
- DELETE /loggers/:logger_type
> Expose logger preferences to admin users

- service_model.go
- service_renderer.go
Fixes : https://github.com/ernestio/ernest/issues/132
> [#ERNEST-132] : Expose last known error to the end user

- service_model.go
- service_renderer.go
- services.go
- user_model.go
Fixes : https://github.com/ernestio/ernest/issues/135
> [#ERNEST_135] : Service belongs to user

- services.go
- setup.go
Fixes : https://github.com/ernestio/ernest/issues/171
> [#ERNEST-171] : Allowed forced service destroys

- service_model.go
- service_renderer.go
Fixes : https://github.com/ernestio/ernest/issues/179
> [#ERNEST-179] : Expose rds endpoints

- .linter.conf
- Makefile
- base_model.go
- circle.yml
- datacenter_model.go
- datacenters.go
- groups.go
- main.go
- service_renderer.go
- services.go
- services_helpers.go
- support_datacenters_test.go
- support_groups_test.go
- support_services_test.go
- support_test.go
- support_users_test.go
- user_model.go
> [#ERNEST-212] : Standarize aws access_key_id and secret_access_key

- service_model.go
- service_renderer.go
Fixes : https://github.com/ernestio/ernest/issues/216
> [#ERNEST-216] : Expose EBS on GET /service/:service

- datacenters_test.go
- services.go
- services_helpers.go
- services_test.go
- setup.go
Fixes : https://github.com/ernestio/ernest/issues/227
> Allow import existing service

- reports.go
- setup.go
- usage_model.go
- usage_renderer.go
Implements https://github.com/ernestio/ernest/issues/295
> [#ERNEST-295] Expose GET /reports/usage/ endpoint

- Makefile
- service_model.go
- service_renderer.go
- services_test.go
implements ernestio/ernest#331
> Output Fix

- loggers.go
implements ernestio/ernest#397
> returning error when deleting a logger fails

- controllers/datacenters.go
- models/datacenter.go
Implements : https://github.com/ernestio/ernest/issues/251
> Azure support

- Makefile
- controllers/auth.go
- helpers/auth.go
- helpers/version.go
Fixes https://github.com/ernestio/ernest/issues/579
> F cli version check 587

- config/routes.go
- controllers/policies.go
- controllers/policies/create.go
- controllers/policies/delete.go
- controllers/policies/get.go
- controllers/policies/list.go
- controllers/policies/update.go
- helpers/auth.go
- models/policy.go
Endpoints to manage policies have been added:
> [#ENTERPRISE-922] : Adding policies basic endpoints
